# Generated by Django 5.2.11 on 2026-02-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('csv_file', models.FileField(upload_to='datasets/')),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
